#!/bin/bash

# Installs all basic/core packages
echo "Y" | apt-get update
echo "Y" | apt-get install git vim openssh-server firefox virtualbox bleachbit tightvncserver gconf-editor python-pip xvfb build-essential module-assistant unzip python-virtualenv network-manager-openvpn-gnome network-manager-openvpn 
sudo m-a prepare

# Installs pyvirtual and xvfb for headless selenium
echo "Y" | apt-get update 
echo "Y" | apt-get upgrade
pip install pyvirtualdisplay selenium
virtualenv env
pip install --upgrade pip
pip install -U selenium

# Add user saqib if not already there
useradd saqib -p saqibkhan
adduser saqib sudo
adduser saqib root

# Gets latest code from github
cd /home/saqib/AutoCoding
git pull
chmod ugo+rwx -R /home/saqib/AutoCoding
chmod ugo+rwx -R /home/saqib/AutoCoding/.git/

cp /home/saqib/AutoCoding/code_base/tools/web_automation_tools/geckodriver /usr/bin/
cp /home/saqib/AutoCoding/code_base/tools/web_automation_tools/environment /etc/
